dist: trusty
sudo: false

language: python
python:
  - "2.7"

notifications:
  email: false

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  pip: true
  directories:
  - "~/.platformio"

env:
  - TEST_PLATFORM="-e megaatmega2560"

before_install:
  #
  # Fetch the tag information for the current branch
  - git fetch origin --tags
  #
  # Publish the buildroot script folder
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/bin/*
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/share/tests/*
  - export PATH=${TRAVIS_BUILD_DIR}/buildroot/bin/:${TRAVIS_BUILD_DIR}/buildroot/share/tests/:${PATH}

install:
  #- pip install -U platformio
  - pip install -U https://github.com/platformio/platformio-core/archive/develop.zip

before_script:
  # Update PlatformIO packages
  - platformio update
  #
  # Change current working directory to the build dir
  - cd ${TRAVIS_BUILD_DIR}
  #
  # Generate custom version include
  - generate_version ${TRAVIS_BUILD_DIR}/Marlin/src/inc
  - cat ${TRAVIS_BUILD_DIR}/Marlin/src/inc/_Version.h
  #
script:
  #
  # Build with the default configurations
  #
  - build_marlin_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
after_success:
  - ls -lh .pioenvs/megaatmega2560/firmware.hex
  - upload_release .pioenvs/megaatmega2560/firmware.hex
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

